name: Doxygen Action
on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master, dev]
jobs:
  generateDocs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: mattnotmitt/doxygen-action@v1.2.3
        with:
          doxyfile-path: './doxyfile'
